// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkCFd00skmk0TFemRGzmJggZenIRS00vA',
    appId: '1:545131713390:web:d844b161cff359b569677f',
    messagingSenderId: '545131713390',
    projectId: 'test-palakat-1',
    authDomain: 'test-palakat-1.firebaseapp.com',
    storageBucket: 'test-palakat-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCJKlNU6uDZoaOUjLlLjcM4eU-mm1Du3A',
    appId: '1:545131713390:android:ea89d6ece529886069677f',
    messagingSenderId: '545131713390',
    projectId: 'test-palakat-1',
    storageBucket: 'test-palakat-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE30Fmr4Ny8hsq7SDgs9TrB8A10nnbVew',
    appId: '1:545131713390:ios:85dde977bef074bd69677f',
    messagingSenderId: '545131713390',
    projectId: 'test-palakat-1',
    storageBucket: 'test-palakat-1.appspot.com',
    iosBundleId: 'com.example.testPalakat1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE30Fmr4Ny8hsq7SDgs9TrB8A10nnbVew',
    appId: '1:545131713390:ios:317322d7da8f062d69677f',
    messagingSenderId: '545131713390',
    projectId: 'test-palakat-1',
    storageBucket: 'test-palakat-1.appspot.com',
    iosBundleId: 'com.example.testPalakat1.RunnerTests',
  );
}
